In [1]:
import torch
import torch.nn as nn

In [2]:
stn_fc1 = nn.Sequential(
    nn.Linear(512, 512),
    nn.BatchNorm1d(512,track_running_stats=False),
    # nn.ReLU(inplace=True)
)
data = torch.ones([2,512])
data.shape
out = stn_fc1(data)
print(out.shape)

torch.Size([2, 512])


In [3]:
import torch
a = torch.randn(16,512)
print(a.shape)
print('='*6)
# a = a.repeat(1000,1,1,2,2) # 这个其实没有意义
a = a.repeat(2,3) # 第0维度重复2次==>16*2=32, 
                  # 第1维度重复3次==>512*3=1536
a.shape

torch.Size([16, 512])


torch.Size([32, 1536])

In [4]:
tensor=torch.tensor([[1,2,3],[4,5,6]])
print(tensor.shape)
tensor

torch.Size([2, 3])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
###  研究 gather 的用法!!
import torch
tensor = torch.tensor([[1,2,3],[4,5,6]])
# 定义索引
index = torch.tensor([[1],[2]])
# 使用gather函数根据索引选取元素
selected_elements = tensor.gather(dim=1, index=index)
print("原始张量:\n", tensor)
print("选取的元素:\n",selected_elements)

原始张量:
 tensor([[1, 2, 3],
        [4, 5, 6]])
选取的元素:
 tensor([[2],
        [6]])


In [2]:
# F.unfold 函数的使用
import torch
import torch.nn.functional as F
img_tensor = torch.randn(1,3,32,32)
patches = F.unfold(img_tensor,kernel_size=(3,3),stride=(1,1))
patches.shape
# 每一个小的patch的像素数量：   channl=3 * kernel_size[0] * kernel_size[1]=27,
# 该图像要划分成的patch的数量： （32-3+1）** 2 = 900
# torch.Size([batch=1, 3*3*3=27, (32-3+1)**2 = 900])

torch.Size([1, 27, 900])

In [1]:
import torch
import torch.nn.functional as F
img_tensor = torch.randn(3,32,32)
patches = F.unfold(img_tensor,kernel_size=(3,3),stride=(1,1))
patches.shape

torch.Size([27, 900])

In [8]:
import torch

# 假设我们有以下连续值
input_values = torch.tensor([0.1,  1.7, 2.5, 5 ])

# 定义桶的边界
boundaries = torch.tensor([0.5, 2.0, 3.5])
"""
[~,0.5]: 桶0
[0.5,2]: 桶1
[2,3.5]: 桶2
[3.5,~]: 桶3

"""
# 桶装化输入值
bucketized_values = torch.bucketize(input_values, boundaries, right=True)
print(bucketized_values)

tensor([0, 1, 2, 3])
