In [1]:
import torch
import torch.nn as nn

In [2]:
stn_fc1 = nn.Sequential(
    nn.Linear(512, 512),
    nn.BatchNorm1d(512,track_running_stats=False),
    # nn.ReLU(inplace=True)
)
data = torch.ones([2,512])
data.shape
out = stn_fc1(data)
print(out.shape)

torch.Size([2, 512])


In [3]:
import torch
a = torch.randn(16,512)
print(a.shape)
print('='*6)
# a = a.repeat(1000,1,1,2,2) # 这个其实没有意义
a = a.repeat(2,3) # 第0维度重复2次==>16*2=32, 
                  # 第1维度重复3次==>512*3=1536
a.shape

torch.Size([16, 512])


torch.Size([32, 1536])

In [4]:
tensor=torch.tensor([[1,2,3],[4,5,6]])
print(tensor.shape)
tensor

torch.Size([2, 3])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
###  研究 gather 的用法!!
import torch
tensor = torch.tensor([[1,2,3],[4,5,6]])
# 定义索引
index = torch.tensor([[1],[2]])
# 使用gather函数根据索引选取元素
selected_elements = tensor.gather(dim=1, index=index)
print("原始张量:\n", tensor)
print("选取的元素:\n",selected_elements)

原始张量:
 tensor([[1, 2, 3],
        [4, 5, 6]])
选取的元素:
 tensor([[2],
        [6]])


In [2]:
# F.unfold 函数的使用
import torch
import torch.nn.functional as F
img_tensor = torch.randn(1,3,32,32)
patches = F.unfold(img_tensor,kernel_size=(3,3),stride=(1,1))
patches.shape
# 每一个小的patch的像素数量：   channl=3 * kernel_size[0] * kernel_size[1]=27,
# 该图像要划分成的patch的数量： （32-3+1）** 2 = 900
# torch.Size([batch=1, 3*3*3=27, (32-3+1)**2 = 900])

torch.Size([1, 27, 900])

In [1]:
import torch
import torch.nn.functional as F
img_tensor = torch.randn(3,32,32)
patches = F.unfold(img_tensor,kernel_size=(3,3),stride=(1,1))
patches.shape

torch.Size([27, 900])

In [8]:
import torch

# 假设我们有以下连续值
input_values = torch.tensor([0.1,  1.7, 2.5, 5 ])

# 定义桶的边界
boundaries = torch.tensor([0.5, 2.0, 3.5])
"""
[~,0.5]: 桶0
[0.5,2]: 桶1
[2,3.5]: 桶2
[3.5,~]: 桶3

"""
# 桶装化输入值
bucketized_values = torch.bucketize(input_values, boundaries, right=True)
print(bucketized_values)

tensor([0, 1, 2, 3])


In [3]:
from torchvision.models import resnet50
import torch
input = torch.ones(1,3,512,512)
# 加载预训练模型
model = resnet50(pretrained=False)
print(model)
output = model(input)
print(f'output.shape:{output.shape}')



ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [4]:
import torch
model.fc = torch.nn.Identity()
print(model)
output = model(input)
print(f'output.shape:{output.shape}')

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [1]:
import torch  
from torch.nn.utils.rnn import pad_sequence  
  
# 假设我们有一批不同长度的序列  
sequences = [  
    torch.tensor([1, 2, 3]),  
    torch.tensor([4, 5]),  
    torch.tensor([6, 7, 8, 9, 10])  
]  
  
# 使用 pad_sequence 填充序列  
padded_sequences = pad_sequence(sequences, batch_first=True, padding_value=0)  
  
print(padded_sequences)

tensor([[ 1,  2,  3,  0,  0],
        [ 4,  5,  0,  0,  0],
        [ 6,  7,  8,  9, 10]])


In [3]:
# -------------------------------------------- #
import torch
a = torch.randn(2)
print(f'a:{a}')

a = torch.randn(2)
print(f'a:{a}')





a:tensor([-0.3479,  0.6531])


In [6]:
# 一些散乱功能的测试
import torch
torch.sqrt(torch.tensor(0))

tensor(0.)

In [7]:
torch.abs(torch.tensor(-1))

tensor(1)

In [9]:
a = 2 - torch.tensor(1)

In [12]:
a.type()

'torch.LongTensor'

In [1]:
import torch

x = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
sigmoid_output = torch.sigmoid(x)
print(sigmoid_output)

tensor([0.7311, 0.8808, 0.9526])


In [2]:
diff = torch.tensor([0.2,0,8,0.1])
torch.where(diff>1,1,0)

tensor([0, 0, 1, 0])

In [1]:
import torch
vector1 = torch.tensor([1.0, 2.0, 3.0])
vector2 = torch.tensor([4.0, 5.0, 6.0])

# 计算两个向量之间的欧氏距离
distance = torch.dist(vector1, vector2)

print("The Euclidean distance between the two vectors is:", distance)

The Euclidean distance between the two vectors is: tensor(5.1962)


In [15]:
######################
import torch
x = torch.tensor([-3.0, 4.0])
norm_L2 = x/torch.norm(x)  # 默认计算 L2 范数
norm_L1 = torch.norm(x, p=1)  # 计算 L1 范数
print(f"norm_L2:{norm_L2}")
print(f"norm_L1:{norm_L1}")

norm_L2:tensor([-0.6000,  0.8000])
norm_L1:7.0


In [16]:
torch.norm(x), torch.sqrt(torch.tensor((-3)**2+4**2))   # torch标准二范数， 自己实现的二范数

(tensor(5.), tensor(5.))

In [17]:
torch.norm(x, p=1), torch.abs(torch.tensor(-3))+torch.abs(torch.tensor(4))   # torch标准1范数， 自己实现的1范数

(tensor(7.), tensor(7))

In [13]:
torch.abs(3)

TypeError: abs(): argument 'input' (position 1) must be Tensor, not int

In [8]:
3.0/torch.sqrt(torch.tensor(3**2+4**2))

tensor(0.6000)

In [4]:
import torch

# 假设 X 是一个二维张量，其中维度 0 是样本索引，维度 1 是特征索引
X = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# 计算每个样本的L2范数
norms = torch.norm(X, p=2, dim=1, keepdim=True)
print(f'norms:{norms}')
# 避免除以零，这里可以添加一个小的常数epsilon来保证数值稳定性
epsilon = 1e-8
normalized_X = X / (norms + epsilon)

print(normalized_X)

norms:tensor([[3.7417],
        [8.7750]])
tensor([[0.2673, 0.5345, 0.8018],
        [0.4558, 0.5698, 0.6838]])


In [18]:
import torch.nn as nn
import numpy as np
nn.Parameter(torch.ones([]) * np.log(1 / 0.07))

Parameter containing:
tensor(2.6593, requires_grad=True)

In [19]:
np.log(1 / 0.07)

2.659260036932778

In [21]:
torch.ones([])  # 牛批了， 这样也可以

tensor(1.)

In [1]:
import torch
x = torch.tensor([[1, 4], [3, 2]])
idx = torch.argsort(x, dim=1)
print(idx)  # 输出: tensor([[0, 1], [0, 1]])

tensor([[0, 1],
        [1, 0]])


In [2]:
import torch
x = torch.tensor([[1, 4], [3, 2]])
idx = torch.argsort(x, dim=0)
print(idx) 

tensor([[0, 1],
        [1, 0]])


In [24]:
import numpy as np
import torch
image = np.random.rand(224, 224, 3)  # 例如，一个224x224的彩色图像
# image

In [26]:
#####################################################################################################################
import torchvision.transforms as transforms
tensor_image = transforms.ToTensor()(image)
transforms.Normalize((0.48145466, 0.4578275, 0.40821073), (0.26862954, 0.26130258, 0.27577711))(tensor_image)






tensor([[[-0.7583, -1.5689,  0.2776,  ...,  1.8083, -0.1192, -1.2107],
         [-0.1495, -1.6791, -0.4729,  ...,  1.4662, -1.1017,  1.9259],
         [ 0.9190, -1.1364,  0.3235,  ..., -0.6855, -1.0217, -1.3685],
         ...,
         [ 1.4315, -0.7207, -1.0956,  ...,  0.3468,  0.2968, -1.6902],
         [ 0.1505,  0.2154, -0.9998,  ...,  1.3882, -0.2843, -0.4890],
         [-0.9517,  1.1820,  1.2287,  ..., -0.3086, -0.7988, -0.8511]],

        [[ 1.4168, -1.3157,  0.2245,  ...,  1.8716,  1.0199, -0.4455],
         [-0.5548,  1.1476,  1.8914,  ...,  1.0708,  1.0865, -0.9958],
         [ 0.0739, -1.6439, -1.2473,  ...,  1.6495, -0.9485, -0.4512],
         ...,
         [-0.0402, -0.6467, -0.5061,  ..., -0.1682, -1.5808,  0.8385],
         [-1.0869, -0.1459,  1.2258,  ..., -0.8428, -1.0872,  1.6223],
         [-1.3766, -1.7472, -0.3195,  ..., -0.7201, -1.5283, -1.3198]],

        [[-1.1557,  1.0700, -0.6480,  ..., -0.6721, -0.4229,  0.3176],
         [ 0.4445, -0.0292,  1.0068,  ...,  0

In [28]:
transforms.Normalize((0.48145466, 0.4578275, 0.40821073), (0.26862954, 0.26130258, 0.27577711))(tensor_image).shape

torch.Size([3, 224, 224])

In [34]:
def preprocess_input(image, mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711)): # 与 transforms.Normalize((0.48145466, 0.4578275, 0.40821073), (0.26862954, 0.26130258, 0.27577711))(tensor_image) 等效
    # 减去均值
    image_normalized = image - mean
    # 除以标准差
    image_normalized = image_normalized / std
    return image_normalized

preprocess_input(image).transpose(2,0,1)

array([[[-0.75832346, -1.56890059,  0.27764618, ...,  1.80828351,
         -0.11917389, -1.21068732],
        [-0.14945518, -1.67906714, -0.47288527, ...,  1.46615433,
         -1.10165183,  1.92592606],
        [ 0.9190179 , -1.13637047,  0.32349601, ..., -0.68548354,
         -1.0217079 , -1.3685119 ],
        ...,
        [ 1.43148797, -0.72071865, -1.09559986, ...,  0.34677549,
          0.29678706, -1.69019295],
        [ 0.15046685,  0.21539279, -0.99975221, ...,  1.38817651,
         -0.28431716, -0.48901073],
        [-0.95173985,  1.18197197,  1.2287448 , ..., -0.30858111,
         -0.79875475, -0.85109897]],

       [[ 1.41680952, -1.31574821,  0.22447754, ...,  1.8715838 ,
          1.01993235, -0.44548069],
        [-0.55484675,  1.14762588,  1.89143368, ...,  1.07077719,
          1.08649702, -0.99582656],
        [ 0.0739356 , -1.6438533 , -1.24731376, ...,  1.6494595 ,
         -0.94851661, -0.45121021],
        ...,
        [-0.04019157, -0.64668819, -0.50606557, ..., -