In [1]:
import torch
import torch.nn as nn

In [2]:
stn_fc1 = nn.Sequential(
    nn.Linear(512, 512),
    nn.BatchNorm1d(512,track_running_stats=False),
    # nn.ReLU(inplace=True)
)
data = torch.ones([2,512])
data.shape
out = stn_fc1(data)
print(out.shape)

torch.Size([2, 512])


In [3]:
import torch
a = torch.randn(16,512)
print(a.shape)
print('='*6)
# a = a.repeat(1000,1,1,2,2) # 这个其实没有意义
a = a.repeat(2,3) # 第0维度重复2次==>16*2=32, 
                  # 第1维度重复3次==>512*3=1536
a.shape

torch.Size([16, 512])


torch.Size([32, 1536])

In [4]:
tensor=torch.tensor([[1,2,3],[4,5,6]])
print(tensor.shape)
tensor

torch.Size([2, 3])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
###  研究 gather 的用法!!
import torch
tensor = torch.tensor([[1,2,3],[4,5,6]])
# 定义索引
index = torch.tensor([[1],[2]])
# 使用gather函数根据索引选取元素
selected_elements = tensor.gather(dim=1, index=index)
print("原始张量:\n", tensor)
print("选取的元素:\n",selected_elements)

原始张量:
 tensor([[1, 2, 3],
        [4, 5, 6]])
选取的元素:
 tensor([[2],
        [6]])


In [2]:
# F.unfold 函数的使用
import torch
import torch.nn.functional as F
img_tensor = torch.randn(1,3,32,32)
patches = F.unfold(img_tensor,kernel_size=(3,3),stride=(1,1))
patches.shape
# 每一个小的patch的像素数量：   channl=3 * kernel_size[0] * kernel_size[1]=27,
# 该图像要划分成的patch的数量： （32-3+1）** 2 = 900
# torch.Size([batch=1, 3*3*3=27, (32-3+1)**2 = 900])

torch.Size([1, 27, 900])

In [1]:
import torch
import torch.nn.functional as F
img_tensor = torch.randn(3,32,32)
patches = F.unfold(img_tensor,kernel_size=(3,3),stride=(1,1))
patches.shape

torch.Size([27, 900])

In [8]:
import torch

# 假设我们有以下连续值
input_values = torch.tensor([0.1,  1.7, 2.5, 5 ])

# 定义桶的边界
boundaries = torch.tensor([0.5, 2.0, 3.5])
"""
[~,0.5]: 桶0
[0.5,2]: 桶1
[2,3.5]: 桶2
[3.5,~]: 桶3

"""
# 桶装化输入值
bucketized_values = torch.bucketize(input_values, boundaries, right=True)
print(bucketized_values)

tensor([0, 1, 2, 3])


In [3]:
from torchvision.models import resnet50
import torch
input = torch.ones(1,3,512,512)
# 加载预训练模型
model = resnet50(pretrained=False)
print(model)
output = model(input)
print(f'output.shape:{output.shape}')



ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [4]:
import torch
model.fc = torch.nn.Identity()
print(model)
output = model(input)
print(f'output.shape:{output.shape}')

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [1]:
import torch  
from torch.nn.utils.rnn import pad_sequence  
  
# 假设我们有一批不同长度的序列  
sequences = [  
    torch.tensor([1, 2, 3]),  
    torch.tensor([4, 5]),  
    torch.tensor([6, 7, 8, 9, 10])  
]  
  
# 使用 pad_sequence 填充序列  
padded_sequences = pad_sequence(sequences, batch_first=True, padding_value=0)  
  
print(padded_sequences)

tensor([[ 1,  2,  3,  0,  0],
        [ 4,  5,  0,  0,  0],
        [ 6,  7,  8,  9, 10]])


In [3]:
# -------------------------------------------- #
import torch
a = torch.randn(2)
print(f'a:{a}')

a = torch.randn(2)
print(f'a:{a}')





a:tensor([-0.3479,  0.6531])


In [6]:
# 一些散乱功能的测试
import torch
torch.sqrt(torch.tensor(0))

tensor(0.)

In [7]:
torch.abs(torch.tensor(-1))

tensor(1)

In [9]:
a = 2 - torch.tensor(1)

In [12]:
a.type()

'torch.LongTensor'

In [1]:
import torch

x = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
sigmoid_output = torch.sigmoid(x)
print(sigmoid_output)

tensor([0.7311, 0.8808, 0.9526])


In [2]:
diff = torch.tensor([0.2,0,8,0.1])
torch.where(diff>1,1,0)

tensor([0, 0, 1, 0])

In [1]:
import torch
vector1 = torch.tensor([1.0, 2.0, 3.0])
vector2 = torch.tensor([4.0, 5.0, 6.0])

# 计算两个向量之间的欧氏距离
distance = torch.dist(vector1, vector2)

print("The Euclidean distance between the two vectors is:", distance)

The Euclidean distance between the two vectors is: tensor(5.1962)


In [3]:
######################
import torch
x = torch.tensor([3.0, 4.0])
norm_L2 = x/torch.norm(x)  # 默认计算 L2 范数
norm_L1 = torch.norm(x, p=1)  # 计算 L1 范数
print(f"norm_L2:{norm_L2}")

norm_L2:tensor([0.6000, 0.8000])


In [4]:
import torch

# 假设 X 是一个二维张量，其中维度 0 是样本索引，维度 1 是特征索引
X = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# 计算每个样本的L2范数
norms = torch.norm(X, p=2, dim=1, keepdim=True)
print(f'norms:{norms}')
# 避免除以零，这里可以添加一个小的常数epsilon来保证数值稳定性
epsilon = 1e-8
normalized_X = X / (norms + epsilon)

print(normalized_X)

norms:tensor([[3.7417],
        [8.7750]])
tensor([[0.2673, 0.5345, 0.8018],
        [0.4558, 0.5698, 0.6838]])
