In [1]:
import torch

In [2]:
# torch.chunk函数的使用
x = torch.arange(12).reshape(3, 4)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [3]:
chunks = torch.chunk(x, 3, dim=0)  # 沿着第0维分成3块
print("分割后的块：")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i}:\n{chunk}")

分割后的块：
Chunk 0:
tensor([[0, 1, 2, 3]])
Chunk 1:
tensor([[4, 5, 6, 7]])
Chunk 2:
tensor([[ 8,  9, 10, 11]])


In [4]:
[  {'DecodeImage':{"a":1,"b":2}}  ]

[{'DecodeImage': {'a': 1, 'b': 2}}]

In [5]:
list({'DecodeImage':{"a":1,"b":2}})

['DecodeImage']

In [6]:
list({'a':1,'b':2})

['a', 'b']

In [ ]:
# torch.cat 的用法!!!
# 功能：将张量在某个维度上进行拼接
a = torch.randn(3, 4)
b = torch.randn(3, 2)
c = torch.randn(3, 5)
torch.cat([a, b, c], dim=1).shape

torch.Size([3, 11])

In [3]:
# torch.amax()的用法
import torch
a = torch.randn(2,3)
# print(a)
print(torch.amax(a))

tensor(1.5901)


In [4]:
print(torch.max(a))

tensor(1.5901)


In [ ]:
# pytorch中的 contiguous() 的作用
"""
哪些操作会导致张量不连续：
    1. 索引操作
    2. 切片操作
    3. 转置操作
作用：
    contiguous() 方法的作用是将一个不连续的张量转换为一个连续的张量。
    它不会改变张量的形状或数据内容，只是重新排列内存中的数据，使得张量在内存中连续存储。
为什么需要 contiguous()：
    在 PyTorch 中，有些操作（如索引、切片、转置等）可能会导致张量的内存不连续，这可能会导致错误或性能问题
    这会影响到后续的操作。因此，在进行这些操作之前，需要使用 contiguous() 方法将张量转换为连续的张量。
    eg:
    view() 方法用于改变张量的形状，但它要求输入张量必须是连续的。如果张量是不连续的，
    直接调用 view() 会导致错误。在这种情况下，需要先调用 contiguous()。
"""

import torch

x = torch.tensor([[1, 2], [3, 4]])
print(x.is_contiguous())  # True

y = x.transpose(0, 1)
print(y.is_contiguous())  # False


True
False
