In [1]:
import torch

In [2]:
# torch.chunk函数的使用
x = torch.arange(12).reshape(3, 4)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [3]:
chunks = torch.chunk(x, 3, dim=0)  # 沿着第0维分成3块
print("分割后的块：")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i}:\n{chunk}")

分割后的块：
Chunk 0:
tensor([[0, 1, 2, 3]])
Chunk 1:
tensor([[4, 5, 6, 7]])
Chunk 2:
tensor([[ 8,  9, 10, 11]])


In [4]:
[  {'DecodeImage':{"a":1,"b":2}}  ]

[{'DecodeImage': {'a': 1, 'b': 2}}]

In [5]:
list({'DecodeImage':{"a":1,"b":2}})

['DecodeImage']

In [6]:
list({'a':1,'b':2})

['a', 'b']

In [ ]:
# torch.cat 的用法!!!
# 功能：将张量在某个维度上进行拼接
a = torch.randn(3, 4)
b = torch.randn(3, 2)
c = torch.randn(3, 5)
torch.cat([a, b, c], dim=1).shape

torch.Size([3, 11])

In [3]:
# torch.amax()的用法
import torch
a = torch.randn(2,3)
# print(a)
print(torch.amax(a))

tensor(1.5901)


In [4]:
print(torch.max(a))

tensor(1.5901)


In [ ]:
# pytorch中的 contiguous() 的作用
"""
哪些操作会导致张量不连续：
    1. 索引操作
    2. 切片操作
    3. 转置操作
作用：
    contiguous() 方法的作用是将一个不连续的张量转换为一个连续的张量。
    它不会改变张量的形状或数据内容，只是重新排列内存中的数据，使得张量在内存中连续存储。
为什么需要 contiguous()：
    在 PyTorch 中，有些操作（如索引、切片、转置等）可能会导致张量的内存不连续，这可能会导致错误或性能问题
    这会影响到后续的操作。因此，在进行这些操作之前，需要使用 contiguous() 方法将张量转换为连续的张量。
    eg:
    view() 方法用于改变张量的形状，但它要求输入张量必须是连续的。如果张量是不连续的，
    直接调用 view() 会导致错误。在这种情况下，需要先调用 contiguous()。
"""

import torch

x = torch.tensor([[1, 2], [3, 4]])
print(x.is_contiguous())  # True

y = x.transpose(0, 1)
print(y.is_contiguous())  # False


True
False


In [13]:
import torch
from torch.utils.checkpoint import checkpoint
import torch.nn as nn

In [15]:
x = torch.randn(3, 5)
nn.ReLU(inplace=True)(x)
# torch.relu(x, inplace=True)

tensor([[0.0000, 0.0000, 1.7821, 0.0000, 1.6577],
        [0.0000, 0.0000, 1.4624, 1.9815, 0.0000],
        [0.4361, 0.0000, 1.6503, 0.4197, 1.5512]])

## nn.ReLU() 中 参数 inplace=True/False 分别代表的含义!
1. inplace=True: 函数执行过程中，将输入的 Tensor 直接修改，并返回该 Tensor。
2. inplace=False: 函数执行过程中，将输入的 Tensor 修改，并返回一个修改后的 Tensor。
3. inplace=True/False 默认值都是 False。

##### 当 inplace=true时有什么优缺点呢？
a. 优点：
    减少内存使用，因为不需要额外的张量来存储结果。
    可以节省时间，因为不需要复制张量。
    节省内存，因为不需要额外的张量来存储结果。
    在内存受限的情况下非常有用。
b. 缺点：
    inplace 操作会改变原始张量，这可能会导致一些问题，例如，如果原始张量被其他地方使用，那么这些地方可能会收到不可expected的结果。
    inplace 操作可能会破坏梯度计算，因为原始张量被修改，这可能会导致梯度计算不正确。
    inplace 操作可能会导致内存泄漏，因为原始张量被修改，但内存不会被释放。
    inplace 操作可能会导致性能问题，因为原始张量被修改，这可能会导致内存使用增加，

我的看法：
   尽量使用 其默认值 inplace=False， 避免出现问题。不在乎这么点显存。

In [ ]:
# --------------------------------- 探究 nn.ReLU() 函数的参数  inplace=True 的反应 --------------------------------
import torch
import torch.nn as nn
import torch.nn.functional as F

x = torch.randn(3,5)
print('raw-x:',x)
x_relu = nn.ReLU(inplace=True)(x)   #  x 的原值直接被修改了
print('after-relu:',x_relu)  # 与上面的x相比，确实发生了变化 (这个司空见惯)
print('is_change_x:', x)     # x 也被原地修改了
print((x==x_relu).all().item())

raw-x: tensor([[-1.2719,  0.5880, -0.3350, -0.4417,  0.3710],
        [-1.0076,  0.2389, -0.1172,  0.1977, -0.2755],
        [ 0.7716,  1.4856,  2.8968,  0.4119, -0.2529]])
after-relu: tensor([[0.0000, 0.5880, 0.0000, 0.0000, 0.3710],
        [0.0000, 0.2389, 0.0000, 0.1977, 0.0000],
        [0.7716, 1.4856, 2.8968, 0.4119, 0.0000]])
is_change_x: tensor([[0.0000, 0.5880, 0.0000, 0.0000, 0.3710],
        [0.0000, 0.2389, 0.0000, 0.1977, 0.0000],
        [0.7716, 1.4856, 2.8968, 0.4119, 0.0000]])
True


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

x = torch.randn(3,5)
print('raw-x:',x)
x_relu = nn.ReLU(inplace=False)(x)   #  x 的原值直接被修改了
print('after-relu:',x_relu)  # 与上面的x相比，确实发生了变化 (这个司空见惯)
print('is_change_x:', x)     # x 本身不会发生变化!!!!
print((x==x_relu).all().item())

raw-x: tensor([[-0.2779,  1.1396,  0.8183,  0.8528, -2.0042],
        [ 0.4544,  0.7078, -0.3485,  0.4805,  0.2434],
        [-0.1929,  0.2803,  1.2087,  0.3692,  1.9432]])
after-relu: tensor([[0.0000, 1.1396, 0.8183, 0.8528, 0.0000],
        [0.4544, 0.7078, 0.0000, 0.4805, 0.2434],
        [0.0000, 0.2803, 1.2087, 0.3692, 1.9432]])
is_change_x: tensor([[-0.2779,  1.1396,  0.8183,  0.8528, -2.0042],
        [ 0.4544,  0.7078, -0.3485,  0.4805,  0.2434],
        [-0.1929,  0.2803,  1.2087,  0.3692,  1.9432]])
False


In [22]:
nn.ReLU(inplace=False)(x)

tensor([[0.9142, 0.0000, 0.1484, 0.1372, 0.6010],
        [0.4923, 0.0000, 0.0000, 1.3964, 0.0000],
        [0.5310, 0.0000, 0.0000, 1.5358, 0.0000]])