In [1]:
import torch

In [2]:
# torch.chunk函数的使用
x = torch.arange(12).reshape(3, 4)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [3]:
chunks = torch.chunk(x, 3, dim=0)  # 沿着第0维分成3块
print("分割后的块：")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i}:\n{chunk}")

分割后的块：
Chunk 0:
tensor([[0, 1, 2, 3]])
Chunk 1:
tensor([[4, 5, 6, 7]])
Chunk 2:
tensor([[ 8,  9, 10, 11]])


In [2]:
[  {'DecodeImage':{"a":1,"b":2}}  ]

[{'DecodeImage': {'a': 1, 'b': 2}}]

In [4]:
list({'DecodeImage':{"a":1,"b":2}})

['DecodeImage']

In [5]:
list({'a':1,'b':2})

['a', 'b']