In [1]:
import torch
import numpy as np
import random

f:\my_softers\project_IDE\Anconda\envs\jp_layout_pytorch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [16]:
# 设置数据类型为float32  
# torch.set_default_dtype(torch.float32)  
torch.set_default_dtype(torch.float16)  
 
# 查询设置后的数据类型  
print(torch.get_default_dtype())


torch.float16


In [19]:
a = torch.tensor([1.7,2.1,3]) # 可见tensor会根据传入的数据类型，确定创建数据的类型
b = torch.tensor([2,3,4])
# torch.dot(a,b)
print('a的数据类型:',a.type())
print('b的数据类型:',b.type())

a的数据类型: torch.HalfTensor
b的数据类型: torch.LongTensor


In [18]:
torch.Tensor([1,2,3]).type() # Tensor会创建数据为默认的数据类型

'torch.HalfTensor'

In [4]:
2+6+12

20

In [5]:
# x = torch.tensor([0.1, 0.2, 0.3])  
x = torch.tensor([1.1, 2.2, 3.3])  
print(x.int() )
print(x.byte() )
print(x.uint8() )

tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.uint8)


AttributeError: 'Tensor' object has no attribute 'uint8'

In [6]:
help(x)

Help on Tensor in module torch object:

class Tensor(torch._C._TensorBase)
 |  Method resolution order:
 |      Tensor
 |      torch._C._TensorBase
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__ = abs(...)
 |  
 |  __array__(self, dtype=None)
 |  
 |  __array_wrap__(self, array)
 |      # Wrap Numpy array again in a suitable tensor when done, to support e.g.
 |      # `numpy.sin(tensor) -> tensor` or `numpy.greater(tensor, 0) -> ByteTensor`
 |  
 |  __contains__(self, element)
 |      Check if `element` is present in tensor
 |      
 |      Args:
 |          element (Tensor or scalar): element to be checked
 |              for presence in current tensor"
 |  
 |  __deepcopy__(self, memo)
 |  
 |  __dir__(self)
 |      Default dir() implementation.
 |  
 |  __floordiv__(self, other)
 |  
 |  __format__(self, format_spec)
 |      Default object formatter.
 |  
 |  __hash__(self)
 |      Return hash(self).
 |  
 |  __ipow__(self, other)
 |  
 |  __iter__(self)
 | 

In [8]:
torch.__version__

'1.8.0+cpu'

In [12]:
"""
tensor之间数据类型的转换
1. 在tensor后加long(),int(),float(),byte() 
    例如：Torch.LongTensor转换为Torch.FloatTensor，直接使用data.float()即可
2. 使用 type()函数
    当data为tensor数据类型, data.type(torch.FloatTensor)则强制将data的数据类型
    转换成torch.FloatTensor类型的张量
3. 当要转换成 另一个数据相同的数据类型时(其中a1与a2是张量类型)
   a1.type_as(a2) # 将a1转换成a2同类型
"""
a = torch.tensor([[1,2,3],[4,5,6]])
# print(a)
print('-'*5,'a*2与a.mul(2)的区别','-'*5)
print('a*2:',a * 2)
print((a.mul(2) == a * 2).all())
print('before-data-type:',a.type())
a = a.to(torch.float32)
# a = a.float()
print('after-data-type:', a.type())
# a.astype(torch.float32) # numpy拥有astype() ,but pytorch 没有
# torch.dtype

----- a*2与a.mul(2)的区别 -----
a*2: tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor(True)
before-data-type: torch.LongTensor
after-data-type: torch.FloatTensor


In [5]:
a.float().type()

'torch.FloatTensor'

In [6]:
# 打印当前torch的版本类型
torch.__version__
# 指定默认数据类型
torch.set_default_tensor_type(torch.DoubleTensor) # torch.cuda.DoubleTensor

<span style='color: red;'>1. Tensors的初始化</span>

In [7]:
# a.直接给值
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print('x_data:',x_data)
# b.从NumPy数组转来
np_arr = np.array([[1,2],[3,4]])
x_np = torch.tensor(np_arr)
print('x_np:',x_np)
x_np1 = torch.from_numpy(np_arr)
print('x_np1:',x_np1)
# -------np_arr与x_np和x_np1都不共享内存-------------
np_arr[0,1] = 44
x_np = torch.tensor(np_arr)
print('x_np_change:',x_np)
x_np1 = torch.from_numpy(np_arr)
print('x_np_change1:',x_np1)
print('id(np_arr):',id(np_arr))
print('id(x_np):',id(x_np))
print('id(x_np1):',id(x_np1))
x_np11 = torch.from_numpy(np_arr)
print('id(x_np11):',id(x_np11))

x_data: tensor([[1, 2],
        [3, 4]])
x_np: tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
x_np1: tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
x_np_change: tensor([[ 1, 44],
        [ 3,  4]], dtype=torch.int32)
x_np_change1: tensor([[ 1, 44],
        [ 3,  4]], dtype=torch.int32)
id(np_arr): 2320485709184
id(x_np): 2320485709128
id(x_np1): 2320485730088
id(x_np11): 2320485730248


In [6]:
torch.eye(4,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [17]:
torch.cat([torch.zeros(1,5).float(), torch.eye(4,5) ,torch.zeros(1,5).float()],dim=0)

tensor([[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0.]])

In [8]:
# 赋01或随机值
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
eye_tensor = torch.eye(5)
print('rand_tensor:',rand_tensor)
print('ones_tensor:',ones_tensor)
print('zeros_tensor:',zeros_tensor)
print('eye_tensor:',eye_tensor)

rand_tensor: tensor([[0.5328, 0.0997, 0.1751],
        [0.5578, 0.1448, 0.7272]])
ones_tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros_tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])
eye_tensor: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])



<span style='color: red;'> 2. Tensors的属性</span>

In [23]:
x = torch.tensor([1.,2.])
x.requires_grad=True
print('x:',x)
print('x.requires_grad:',x.requires_grad)
print('x--:',x.data)

x: tensor([1., 2.], requires_grad=True)
x.requires_grad: True
x--: tensor([1., 2.])


In [17]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
x = torch.tensor([1,2])
print('x.data:',x.data)       # tensor([1, 2])
print('x.is_leaf:',x.is_leaf) # True 
print('x.shape:',x.shape)     # x.shape: torch.Size([2])
print('x.size:',x.size())     # x.size: torch.Size([2])
print('x.dtype:',x.dtype) # 推荐使用 x.type()查看数据类型   -- x.dtype: torch.int64
print('x.device:',x.device) # x.device: cpu
print('x.requires_grad',x.requires_grad) # x.requires_grad False
#-----------------
# 1. 修改tensor的dtype
# 注意: .to()方法会返回一个新的tensor,他们不共用内存
print(id(x))
x_change_dtype1 = x.to(torch.int32)
x_change_dtype2 = x.float()
# x_change_dtype3 = x.to_(torch.float64)
print('x_change_dtype.dtype:',x_change_dtype1.dtype)
print('id(x-raw)',id(x))
print('id(x_change_dtype1)',id(x_change_dtype1))
print('id(x_change_dtype2)',id(x_change_dtype2))
# print('id(x_change_dtype3)',id(x_change_dtype3))

x.data: tensor([1, 2])
x.is_leaf: True
x.shape: torch.Size([2])
x.size: torch.Size([2])
x.dtype: torch.int64
x.device: cpu
x.requires_grad False
1853277836536
x_change_dtype.dtype: torch.int32
id(x-raw) 1853277836536
id(x_change_dtype1) 1853277837096
id(x_change_dtype2) 1851231986696


<span style="color: red;">3.各种操作</span>

In [ ]:
# 设置随机种子(非必须)

# a. 可以定义一个随机种子的函数(以后很可能通用了)
def setup_seed(seed):
    # 1. 设置pytorch的随机种子
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    # 2. 设置其他第3方库的随机变量
    np.random.seed(seed)
    random.seed(seed)
    

m_seed = 20
torch.manual_seed(m_seed)
# setup_seed(m_seed)
torch.cuda.manual_seed_all(m_seed)

# *** 索引和切片操作
x = torch.rand(3,4)
print('*******-------索引和切片操作-------*******')
print('x:',x)
print('x[0]',x[0]) # 第0行
print('x[:,0]',x[:,0]) # 第0列的全部元素 
print('x[...,0]',x[...,0]) # 第0列的全部元素 

# *** 拼接操作
print('*******-------拼接操作-------*******')
x = torch.ones(4,3)
y = torch.zeros(3,3)
# print('x:',x)
# print('y:',y)
out = torch.cat([x,y],dim=0)
print(out)
# *** 矩阵乘法
print('*******-------矩阵乘法-------*******')

# 1). torch.mul(a,b)=a*b -------> 按元素乘(可能会触发广播机制)
print('----按照元素相乘----')
x_1 = torch.ones(4,3)
x_2 = torch.ones(4,1)*1.2
out_1 = x_1 * x_2
print('out_1:',out_1)
out_2 = torch.mul(x_1,x_2)
print('out_2:',out_2)
# 2). torch.mm(a,b) ---> 矩阵乘法 (a/b必须是二维的张量) ---> a=(x,n), b=(n,y)
x_1 = torch.rand(5,3) # 均匀分布
x_2 = torch.randn(3,4) # 正态分布
out_3 = torch.mm(x_1,x_2)
print('out_3:', out_3.shape) # (5,4)
# 3). torch.bmm ---> 第0维为batch_size意义的矩阵乘法(a/b必须是三维的张量) ---> a=(bs,x,n) b=(bs,n,y)
x_1 = torch.rand(32,5,3) # 均匀分布
x_2 = torch.randn(32,3,4) # 正态分布
out_4 = torch.bmm(x_1,x_2)
print('out_4:', out_4.shape) # (32,5,4)
# 4). torch.dot ---> 点积(a/b必须是一维向量) --> a=(m) b=(m) 返回按元素乘后的求和结果，即点积结果。
x_1 = torch.rand(5) # 均匀分布
x_2 = torch.randn(5) # 正态分布
out_5 = torch.dot(x_1,x_2)
print('out_5:', out_5) # tensor(1.1179)

*******-------索引和切片操作-------*******
x: tensor([[0.5615, 0.1774, 0.8147, 0.3295],
        [0.2319, 0.7832, 0.8544, 0.1012],
        [0.1877, 0.9310, 0.0899, 0.3156]])
x[0] tensor([0.5615, 0.1774, 0.8147, 0.3295])
x[:,0] tensor([0.5615, 0.2319, 0.1877])
x[...,0] tensor([0.5615, 0.2319, 0.1877])
*******-------拼接操作-------*******
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
*******-------矩阵乘法-------*******
----按照元素相乘----
out_1: tensor([[1.2000, 1.2000, 1.2000],
        [1.2000, 1.2000, 1.2000],
        [1.2000, 1.2000, 1.2000],
        [1.2000, 1.2000, 1.2000]])
out_2: tensor([[1.2000, 1.2000, 1.2000],
        [1.2000, 1.2000, 1.2000],
        [1.2000, 1.2000, 1.2000],
        [1.2000, 1.2000, 1.2000]])
out_3: torch.Size([5, 4])
out_4: torch.Size([32, 5, 4])
out_5: tensor(1.1179)


In [ ]:
# torch.matmul (该函数较复杂,需要分情况讨论)
# 1. a为1D向量, b为1D向量, torch.matmul(a,b)返回点积标量
a = torch.rand(5)
b = torch.randn(5)
c = torch.matmul(a,b)
print(c)
# 2. a为2D向量, b为2D向量, torch.matmul(a,b)返回矩阵乘法的结果
a = torch.rand(3,5)
b = torch.randn(5,4)
c = torch.matmul(a,b)
print(c.shape)
# https://zhuanlan.zhihu.com/p/576893207?utm_id=0

tensor(-2.5310)
torch.Size([3, 4])


<span style="color: red;">4. 数据集和数据加载器</span>

In [ ]:
import torch
import numpy as np

f:\my_softers\project_IDE\Anconda\envs\jp_layout_pytorch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a = np.ones((2,3))
b = torch.ones(2,3)
c = torch.ones((2,3))
# b与c是等效的

In [ ]:
a.size()

TypeError: 'int' object is not callable

In [ ]:
c.size()

torch.Size([2, 3])

In [ ]:
a = np.random.randn(2,3)
b = torch.randn(2,3)
c = torch.randn((2,3))

In [ ]:
a.size

6

In [ ]:
b.size(0)

2

In [24]:
c = torch.rand(7, 32, 8)
aa,bb,cc = c.chunk(3, dim=0)  # 第1个参数要拆分后的数量
# len(aa)
print(aa.shape)
print(bb.shape)
print(cc.shape)

torch.Size([3, 32, 8])
torch.Size([3, 32, 8])
torch.Size([1, 32, 8])


In [26]:
c[:3,...].shape

torch.Size([3, 32, 8])

In [27]:
##### .data .detach()
a = torch.ones(3,2)
a.requires_grad=True
c = a.data
d = a.detach()
print(f'a:{id(a)}\nc:{id(c)}\nd:{id(d)}')
print('-='*10)
print(f'a:{a.requires_grad}\nc:{c.requires_grad}\nd:{d.requires_grad}')

a:2004286256056
c:2004286746856
d:2004286746936
-=-=-=-=-=-=-=-=-=-=
a:True
c:False
d:False


In [6]:
import torch
a = torch.randint(0, 2,(4,2)).bool()
print(a)
print(torch.all(a, dim=1))
print(torch.all(a, dim=0))

tensor([[False,  True],
        [False,  True],
        [False,  True],
        [False,  True]])
tensor([False, False, False, False])
tensor([False,  True])
