In [10]:
import numpy as np
x = np.arange(4)
y = np.arange(4,7)
print(f'x:{x}')
print(f'y:{y}')

x:[0 1 2 3]
y:[4 5 6]


In [11]:
xx, yy = np.meshgrid(x,y)

In [12]:
print(f"xx:{xx}")  # x 为生成矩阵xx的x轴，在y轴上复制len(y)份
print("="*10)
print(f"yy:{yy}")  # y 为生成矩阵yy的y轴，在x轴上复制len(x)份

xx:[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
yy:[[4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]
