In [2]:
import cv2
import numpy as np
im1 = cv2.imread('./imgs/0.jpg')
im2 = cv2.imread('./imgs/1.jpg')

In [3]:
# shi-Tomasi是Harris角点检测的改进

In [7]:
gray = cv2.cvtColor(im1, cv2.COLOR_BGR2GRAY)
gray = np.float32(gray)
maxCorners = 1000  # 检测最大的角点数量
ql = 0.01      # 可接受的最小角点质量的阈值，低于这个阈值的角点被拒绝
minDistance = 10   # 表示返回的角点之间的最小可能的欧式距离
# shi-tomasi 角点检测
# 
# 
# 
corners = cv2.goodFeaturesToTrack(gray, maxCorners, ql, minDistance)
corners

array([[[1865.,  706.]],

       [[1873.,  510.]],

       [[1978.,  823.]],

       ...,

       [[2281.,  950.]],

       [[2274., 1048.]],

       [[2461., 1065.]]], dtype=float32)

In [11]:
# harris角点的展示
# 对检测结果进行膨胀，以便标记角点
corners = np.intp(corners)
for corner in corners:
    print(f'corner:{corner}')
    x, y = corner.ravel()
    cv2.circle(im1, (x,y), 3, (255,0,0), -1)
    

window_name = 'Image Window'  
cv2.namedWindow(window_name, cv2.WINDOW_NORMAL) 
cv2.resizeWindow(window_name, 2000, 1080) 
cv2.imshow(window_name,im1)
cv2.waitKey(0)

corner:[[1865  706]]
corner:[[1873  510]]
corner:[[1978  823]]
corner:[[1038  539]]
corner:[[1689  394]]
corner:[[1842  901]]
corner:[[1840  727]]
corner:[[1852  694]]
corner:[[2136  791]]
corner:[[1691  430]]
corner:[[1861  762]]
corner:[[1050  562]]
corner:[[1963  912]]
corner:[[2341  829]]
corner:[[1888  505]]
corner:[[2219  809]]
corner:[[2234  847]]
corner:[[1037  549]]
corner:[[1024  470]]
corner:[[1866  785]]
corner:[[1002  508]]
corner:[[1021  553]]
corner:[[2089  690]]
corner:[[2136  716]]
corner:[[2194  753]]
corner:[[2062  869]]
corner:[[1038  491]]
corner:[[1757  475]]
corner:[[1869  524]]
corner:[[1023  458]]
corner:[[1879  494]]
corner:[[2101  679]]
corner:[[2026  816]]
corner:[[2343  844]]
corner:[[1847  762]]
corner:[[991 494]]
corner:[[2272  849]]
corner:[[1064  551]]
corner:[[2280  827]]
corner:[[1660  676]]
corner:[[1868  489]]
corner:[[2090  704]]
corner:[[1052  575]]
corner:[[1837  817]]
corner:[[1740  356]]
corner:[[2285  935]]
corner:[[1060  563]]
corner:[[1456  

-1

In [16]:
import numpy as np
a = np.array([[1.2,2.3]])
a

array([[1.2, 2.3]])

In [17]:
a.ravel()

array([1.2, 2.3])