In [34]:
import tools.op_faiss as op
faissor = op.OP_FAISS(test_mode=True)
faissor.get_index_info()

coming.........
test_mode:True
正处在测试模式下。。。。。。。==
self.vector_db= (1000, 64) 

self.vector_query= (100, 64) 

index.is_trained= True
index-num:1000
index-num:1000
index-dim:64
index_is_trained:True


In [35]:

top_k_distance_l, top_k_index_l = faissor.similar_search(5)


In [36]:
top_k_distance_l[:4,:] # 由于度量方式为faiss.METRIC_INNER_PRODUCT(内积)，则表示距离越大，越相似

array([[0.8422754 , 0.833924  , 0.8306502 , 0.8283089 , 0.8268902 ],
       [0.8456702 , 0.8440767 , 0.84254515, 0.83833903, 0.83751345],
       [0.8560995 , 0.84404635, 0.84285617, 0.83954555, 0.8323739 ],
       [0.8669453 , 0.84248483, 0.8403381 , 0.83703303, 0.83030903]],
      dtype=float32)

In [37]:
top_k_index_l[:4,:]

array([[250, 429, 868, 973, 970],
       [932, 208, 550,  52, 916],
       [473,  50, 246, 247, 632],
       [214, 755, 175, 647, 442]], dtype=int64)

In [38]:
top_k_distance_l, top_k_index_l = faissor.similar_search(6)

In [39]:
top_k_distance_l[:4,:]

array([[0.8422754 , 0.833924  , 0.8306502 , 0.8283089 , 0.8268902 ,
        0.8261725 ],
       [0.8456702 , 0.8440767 , 0.84254515, 0.83833903, 0.83751345,
        0.8330647 ],
       [0.8560995 , 0.84404635, 0.84285617, 0.83954555, 0.8323739 ,
        0.83019453],
       [0.8669453 , 0.84248483, 0.8403381 , 0.83703303, 0.83030903,
        0.82751095]], dtype=float32)

In [43]:
# 获取索引号为0的向量
faissor.index.reconstruct(0)

array([0.0398863 , 0.12956186, 0.09116223, 0.16356067, 0.16243964,
       0.05677079, 0.05757711, 0.16699983, 0.1995444 , 0.18242383,
       0.07451988, 0.10433844, 0.14233963, 0.14842904, 0.07710931,
       0.11687607, 0.10477331, 0.00286745, 0.16095072, 0.18382098,
       0.07599203, 0.12816389, 0.01569908, 0.07681217, 0.194338  ,
       0.13565758, 0.08272237, 0.16426283, 0.06598505, 0.11831359,
       0.18100655, 0.09083852, 0.16705719, 0.02994122, 0.14667107,
       0.1467378 , 0.04556617, 0.19261515, 0.09208129, 0.18937632,
       0.01245601, 0.03838007, 0.00986232, 0.14055233, 0.12383798,
       0.11106846, 0.00902277, 0.1169254 , 0.06865754, 0.10474908,
       0.02330338, 0.12645562, 0.117865  , 0.0014087 , 0.1285899 ,
       0.1899609 , 0.16463645, 0.20661327, 0.19968235, 0.16493635,
       0.05940705, 0.13014665, 0.09956896, 0.04075178], dtype=float32)

In [40]:
faissor.load_index('test.index')

In [41]:
faissor.get_index_info()

index-num:1000
index-dim:64
index_is_trained:True


In [3]:
from torchvision.models import resnet50
import torch
input = torch.ones(1,3,512,512)
# 加载预训练模型
model = resnet50(pretrained=False)
print(model)
output = model(input)
print(f'output.shape:{output.shape}')

d:\anaconda\envs\pt\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
d:\anaconda\envs\pt\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)


ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [4]:
import torch
model.fc = torch.nn.Identity()
print(model)
output = model(input)
print(f'output.shape:{output.shape}')

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [ ]:
# python 字典持久化
