In [1]:
import numpy as np

## 模拟模拟

In [2]:
# 可用于分割网络数据的生成
data_dict = {
    "img": np.array([1,2,3]),
    "label": np.array([4,5,6])
}
np.savez("data.npz", **data_dict)

In [3]:
# 可用于分割网络数据的读取
data = np.load('data.npz')
img = data["img"]
label = data["label"]
data.close() # 记得关闭文件

## 实战实战

In [4]:
import numpy as np
data = np.load('scene_hou_train.npz', allow_pickle='True')
data

NpzFile 'scene_hou_train.npz' with keys: image_paths, depth_paths, intrinsics, poses, pair_infos

In [10]:
print(f'image_paths:{data["image_paths"]}')
print(f'depth_paths:{data["depth_paths"]}')
print(f'intrinsics:{data["intrinsics"]}')
print(f'poses:{data["poses"]}')
print(f'pairs_info:{data["pair_infos"]}')

image_paths:[None 'images\\wz0602001-10.jpg' 'images\\wz0602001-6.jpg'
 'images\\wz0602001-7.jpg' 'images\\wz0602001-8.jpg']
depth_paths:[None 'depth\\wz0602001-10.h5' 'depth\\wz0602001-6.h5'
 'depth\\wz0602001-7.h5' 'depth\\wz0602001-8.h5']
intrinsics:[[[None None None]
  [None None None]
  [None None None]]

 [[11638.411226873428 0.0 1045.0]
  [0.0 10132.691431748926 144.0]
  [0.0 0.0 1.0]]

 [[11638.411226873428 0.0 1045.0]
  [0.0 10132.691431748926 144.0]
  [0.0 0.0 1.0]]

 [[11638.411226873428 0.0 1045.0]
  [0.0 10132.691431748926 144.0]
  [0.0 0.0 1.0]]

 [[11638.411226873428 0.0 1045.0]
  [0.0 10132.691431748926 144.0]
  [0.0 0.0 1.0]]]
poses:[[[None None None None]
  [None None None None]
  [None None None None]
  [None None None None]]

 [[0.9383666355992721 0.3275682681947234 -0.11030451879235297
   -0.7018524501140527]
  [-0.33479964806917595 0.9407082259715085 -0.0545639921770157
   -0.6711045664909996]
  [0.08589093576657979 0.0881309438361308 0.992398953995667
   -22.6312