In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])
b = np.array([[10,20],[30,40]])

In [3]:
a+b

array([[11, 22],
       [33, 44]])

In [4]:
a + 5

array([[6, 7],
       [8, 9]])

<span style='color:red;'>2. 看看numpy的广播机制</span>

In [7]:
a = np.array([[1,2]])
b = np.array([[1,2],[3,4]])
a+b        

array([[2, 4],
       [4, 6]])

In [8]:
a = np.array([1,2])
b = np.array([[1,2],[3,4]])
a+b   

array([[2, 4],
       [4, 6]])