In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a[[1,2],0]

array([4, 8])

In [24]:
a[1,2] # 1行2列
a[1:,2:] # [[6,7],[10,11]]
a[[1,2]] # 获取第1，2行的所有元素
# 总结： 其实可以将 [1,2]看成是一个整体，以','作为划分不同维度的标志

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
a = np.arange(10)
np.where(a>5)
a[a>5]
np.any(a>5) # True
np.all(a>5)  # False

False

In [26]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a[:,:,None].shape

(3, 4, 1)

In [28]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
np.expand_dims(a,-1).shape

(3, 4, 1)

In [33]:
np.all(np.expand_dims(a,-1) == a[:,:,None] )

True

In [32]:
np.all(np.expand_dims(a,-1) ==  a[...,None])

True