In [1]:
import numpy as np

In [3]:
np_a = np.arange(16).reshape(4,4)
np_a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
np.diag(np_a)

array([ 0,  5, 10, 15])

In [5]:
np.random.randint(16)

4

In [20]:
#### 手动写一个函数求一个方阵的对角线（向上或下）上元素的索引
def diag_index(n, direction='up'):
    """ 1. nomove: 获取对角线位置的索引
        2. up: 获取对角线向右上一个位置的索引 
        3. down: 获取对角线向左下一个位置的索引
        4. 其他: 获取去除1，2，3以外的索引
        右上或 左下 放下移动一个位置后的元素索引 """
    if direction == 'up': # 向右上方移动一个位置
        return [(i, i+1) for i in range(n-1) if i+1 < n ]
    elif direction == 'down': # 向左下方移动一个位置
        return [(i, i-1) for i in range(1,n) if i < n ]
    elif direction == 'nomove': # 不移动
        return [(i, i) for i in range(n)]
    else:
        special_loc = diag_index(n, direction='up') + diag_index(n, direction='down') +  diag_index(n, direction='nomove') 
        full_n_square = [(i,j) for i in range(n) for j in range(n)]
        return list(set(full_n_square) - set(special_loc))
res = diag_index(4,'up') 
res

[(0, 1), (1, 2), (2, 3)]

In [21]:
res = diag_index(4,direction='down') 
res

[(1, 0), (2, 1), (3, 2)]

In [23]:
diag_index(4,'up') + diag_index(4,direction='down') 

[(0, 1), (1, 2), (2, 3), (1, 0), (2, 1), (3, 2)]

In [12]:
res = diag_index(4,direction='nomove') 
res

[(0, 0), (1, 1), (2, 2), (3, 3)]

In [13]:
res = diag_index(4,direction='1332') 
res

[(3, 1), (0, 3), (2, 0), (3, 0), (0, 2), (1, 3)]

In [ ]:
# 一次性生成所有的索引， 简单高效
def diag_index(n):
    """ 1. nomove: 获取对角线位置的索引
        2. up: 获取对角线向右上一个位置的索引 
        3. down: 获取对角线向左下一个位置的索引
        4. 其他: 获取去除1，2，3以外的索引
        右上或 左下 放下移动一个位置后的元素索引 """
    return_loc_dict = {
        "up": [(i, i+1) for i in range(n-1) if i+1 < n ],
        "down": [(i, i-1) for i in range(1,n) if i < n ],
        "nomove": [(i, i) for i in range(n)],
    }    
    return_loc_dict["other"] = [(i,j) for i in range(n) for j in range(n) if (i,j) not in return_loc_dict["up"] + return_loc_dict["down"] + return_loc_dict["nomove"]] 
    
    return return_loc_dict
res = diag_index(4)

In [18]:
res["up"], res["down"], res["nomove"], res["other"]

([(0, 1), (1, 2), (2, 3)],
 [(1, 0), (2, 1), (3, 2)],
 [(0, 0), (1, 1), (2, 2), (3, 3)],
 [(0, 2), (0, 3), (1, 3), (2, 0), (3, 0), (3, 1)])

In [25]:
[None] * 2**3

[None, None, None, None, None, None, None, None]

In [27]:
a = { 3:'d', 1:'b', 0:'a', 2:'c'}
sorted_values = [a[key] for key in sorted(a.keys())]
sorted_values

['a', 'b', 'c', 'd']

In [1]:
import numpy as np
data = np.random.uniform(0, 255, 128).astype(np.float32)
data

array([3.8782009e+01, 2.3665916e+02, 1.9449043e+02, 2.5323450e+02,
       2.3389380e+02, 1.4250766e+02, 4.2749741e+01, 2.2846112e+02,
       1.5837097e+02, 1.4232077e+02, 1.5772246e+02, 6.0764626e+01,
       5.4387257e+01, 1.9572173e+02, 1.1705537e+02, 2.0624529e+02,
       2.0540117e+02, 9.6767807e+01, 1.4359366e+02, 1.0294029e+02,
       1.1756977e+01, 1.5789133e+02, 9.5256126e+01, 2.3440977e+02,
       2.1812683e+02, 1.7290746e+02, 1.4939090e+02, 1.2532801e+02,
       2.0260066e+02, 1.8691904e+02, 9.8325333e+01, 8.6112923e+01,
       3.4101368e+01, 1.8794786e+02, 5.7323277e+01, 7.5846882e+00,
       3.1486025e+01, 1.1775217e+02, 4.9404579e+01, 1.3877206e+01,
       2.4449465e+01, 2.1342648e+02, 1.7638165e+02, 1.8199333e+02,
       1.6065839e+02, 1.0571059e+02, 1.7807835e+02, 6.8252838e+01,
       3.7138638e+01, 2.1622963e+02, 5.5446766e+01, 1.6141901e+02,
       1.9059184e-01, 2.2001476e+02, 4.4747555e+01, 2.1311925e+02,
       2.0110329e+02, 3.6924889e+01, 8.9662872e+01, 1.7399100e