In [23]:
import numpy as np
from random import shuffle,seed

In [28]:
# 对一个数组的一种统一打乱方式   多组数据统一打乱， 还一一对应的打乱方式
a = np.array(['a','b','c','d','e','f','g'],dtype=object)
b = np.array(['aa','bb','cc','dd','ee','ff','gg'],dtype=object)
print("-"*5,'打乱之前的数据','-'*5)
print(f'a:{a}')
print(f'b:{b}')
print("-"*5,'打乱之后的数据','-'*5)
shuffle_index =  np.arange(len(a))
# seed(10100)
shuffle(shuffle_index)
a = a[shuffle_index]
b = b[shuffle_index]
print(f'shuffle_index:{shuffle_index}')
print(f'a:{a}')
print(f'b:{b}')

----- 打乱之前的数据 -----
a:['a' 'b' 'c' 'd' 'e' 'f' 'g']
b:['aa' 'bb' 'cc' 'dd' 'ee' 'ff' 'gg']
----- 打乱之后的数据 -----
shuffle_index:[4 6 2 1 3 5 0]
a:['e' 'g' 'c' 'b' 'd' 'f' 'a']
b:['ee' 'gg' 'cc' 'bb' 'dd' 'ff' 'aa']


In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a[[1,2],0]

array([4, 8])

In [24]:
a[1,2] # 1行2列
a[1:,2:] # [[6,7],[10,11]]
a[[1,2]] # 获取第1，2行的所有元素
# 总结： 其实可以将 [1,2]看成是一个整体，以','作为划分不同维度的标志

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
a = np.arange(10)
np.where(a>5)
a[a>5]
np.any(a>5) # True
np.all(a>5)  # False

False

In [26]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a[:,:,None].shape

(3, 4, 1)

In [28]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
np.expand_dims(a,-1).shape

(3, 4, 1)

In [33]:
np.all(np.expand_dims(a,-1) == a[:,:,None] )

True

In [32]:
np.all(np.expand_dims(a,-1) ==  a[...,None])

True