In [1]:
import numpy as np
import torch    
from random import randrange

In [5]:
randrange(10)

5

In [5]:
a = np.random.rand(12,10,8)
a[:,0].shape

(12, 8)

In [6]:
import re
text = (
    'Hello, how are you? I am Romeo.\n'
    'Hello, Romeo My name is Juliet. Nice to meet you.\n'
    'Nice meet you too. How are you today?\n'
    'Great. My baseball team won the competition.\n'
    'Oh Congratulations, Juliet\n'
    'Thanks you Romeo'
)
sentences = re.sub("[.,!?\\-]", '', text.lower()).split('\n')  # filter '.', ',', '?', '!'
word_list = list(set(" ".join(sentences).split()))

In [7]:
sentences

['hello how are you i am romeo',
 'hello romeo my name is juliet nice to meet you',
 'nice meet you too how are you today',
 'great my baseball team won the competition',
 'oh congratulations juliet',
 'thanks you romeo']

In [ ]:
word_list


['how',
 'romeo',
 'baseball',
 'team',
 'meet',
 'are',
 'competition',
 'juliet',
 'thanks',
 'too',
 'am',
 'to',
 'great',
 'today',
 'name',
 'nice',
 'you',
 'the',
 'i',
 'hello',
 'my',
 'won',
 'is',
 'congratulations',
 'oh']

: 

In [13]:
# a = torch.from_numpy(np.array([1, 2, 3]))
a = np.array([1, 2, 3])
b = torch.tensor([4, 5, 6])
a+b

TypeError: Concatenation operation is not implemented for NumPy arrays, use np.concatenate() instead. Please do not rely on this error; it may not be given on all Python implementations.

In [21]:
scores = torch.tensor([100., 101., 102.])
print(torch.softmax(scores, dim=0))
scores_ = torch.tensor([10000., 10001., 10002.])
print(torch.softmax(scores_,dim=0))

tensor([0.0900, 0.2447, 0.6652])
tensor([0.0900, 0.2447, 0.6652])


In [ ]:
np.triu(np.ones(5), k=1)# .astype(bool)

array([[False,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False, False,  True,  True],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [142]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [148]:
a[3:0:-2]

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [111]:
import numpy as np

x = np.array([0, 1, 1, 3, 2, 1, 7])
"""
注意：x必须是一维的且只包含非负整数。
对数组中的非负整数进行计数，返回一个数组，数组的索引表示原数组中的值，值表示该索引值在原数组中出现的次数。

"""
result = np.bincount(x)     # =====> 默认返回 数组中最大的数字 +1 的长度
# result = np.bincount(x, minlength=10)  ## ====》 当 minlength < 最大数字 +1 时，返回 minlength 的长度
#                                        ## 当 minlength > 最大数字 +1 时，返回 minlength 的长度，且多出来的部分用0填充 
print(result)
"""
[
 1 : 数字0出现1次
 3 : 数字1出现3次
 1 : 数字2出现1次
 1 : 数字3出现1次
 0 : 数字4出现0次
 0 : 数字5出现0次
 0 : 数字6出现0次
 1 : 数字7出现1次
]

"""

[1 3 1 1 0 0 0 1]


'\n[\n 1 : 数字0出现1次\n 3 : 数字1出现3次\n 1 : 数字2出现1次\n 1 : 数字3出现1次\n 0 : 数字4出现0次\n 0 : 数字5出现0次\n 0 : 数字6出现0次\n 1 : 数字7出现1次\n]\n\n'

In [112]:
np.arange(0.4,1,0.4)

array([0.4, 0.8])

In [113]:
a = np.ones((512,512,1))
a.shape

(512, 512, 1)

In [114]:
a.repeat(3, axis=-1).shape

(512, 512, 3)

In [115]:
np.triu(np.ones((3,3)), k=0)

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [116]:
np.triu(np.ones((3,3)), k=1)

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [117]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.triu(arr,k=1)

# 上3角区域保持不变
# 其他地方变成0


array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [118]:
a = np.random.randint(0,10,(2,2))
b = np.random.randint(0,10,(2,2))
print('-'*6)
print(a)
print('-'*6)
print(b)

------
[[9 0]
 [7 4]]
------
[[7 2]
 [5 5]]


In [119]:
# 这个一般用在哪里呢？！！！
np.fmax(a,b)  # 从a，b的对应位置处找到最大的值

array([[9, 2],
       [7, 5]], dtype=int32)

In [120]:
np.where(a>b,a,b) # 有条件又有对应条件的值，则返回对应条件的值

array([[9, 2],
       [7, 5]], dtype=int32)

In [121]:
a=np.random.randn(2,2)
a

array([[-0.5566051 , -0.07827693],
       [ 0.98073591, -2.06007812]])

In [122]:
a.min(1)

array([-0.5566051 , -2.06007812])

In [123]:
a = np.arange(9)
res = np.where(a>2) # # 当只有条件时，返回索引
res

(array([3, 4, 5, 6, 7, 8]),)

In [124]:
import numpy as np
a = np.array([2,4,6,8,10])
np.where(a>5)

(array([2, 3, 4]),)

In [125]:
res[0]

array([3, 4, 5, 6, 7, 8])

In [126]:
h_array = np.zeros(100, dtype=np.int32)
np.where(h_array==0)[0] # 当只有条件时，返回索引

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [127]:
a = np.arange(9)
np.where(a>2,'yes','no')

array(['no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'],
      dtype='<U3')

In [128]:
a = np.arange(9)
np.where(a>2,'yes','no')

array(['no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'],
      dtype='<U3')

In [129]:
# 主动使用广播机制
a = np.array([1,2,3])
b = np.broadcast_to(a,(3,3))
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [130]:
print(np.max([1,2]))
print(max([1,2]))

2
2


In [131]:
import numpy as np

In [132]:
a = np.array([123, 2, 255, 289])
a

array([123,   2, 255, 289])

In [133]:
np.where(a>255, 255, a)

array([123,   2, 255, 255])

In [134]:
np.uint8(a)

array([123,   2, 255,  33], dtype=uint8)

In [135]:
[1,2,3,4,5,5,5].index(5)

4

In [136]:
[1,2,3,4,5,5,5].index(1)

0

In [137]:
list1 = ['a', 1,      'b',3,4,5,6,  'c']
list2 = ['a', 11, 22, 'b',33,       'c']

In [138]:
l1_point1 = list1.index('a')
l1_point2 = list1.index('b')
l1_point3 = list1.index('c')
l1_point_l = [l1_point1, l1_point2, l1_point3]

In [139]:
l2_point1 = list2.index('a')
l2_point2 = list2.index('b')
l2_point3 = list2.index('c')
l2_point_l = [l2_point1, l2_point2, l2_point3]

In [140]:
def fill_null(list1, list2):
    

SyntaxError: incomplete input (3498122524.py, line 2)

In [ ]:
def merge_lists(list1, list2):
    """
    假定list1 与 list2 的头尾的元素一定是相同的

    """
    
    


In [ ]:
list1 = ['a', 1,      'b',3,4,5,6,  'c']
list2 = ['a', 11, 22, 'b',33,       'c']

In [ ]:
list1+list2

In [ ]:
import numpy as np
array_of_objects = np.empty(3, dtype=np.object)
array_of_objects[0] = 'a string'
array_of_objects[1] = [1, 2, 3]
array_of_objects[2] = {'a': 1, 'b': 2}
print(array_of_objects)

In [ ]:
def longest_increasing_subsequence(arr):
    if not arr:
        return 0

    n = len(arr)
    dp = [1] * n  # 初始化 dp 数组，每个元素的最小上升子序列长度为 1

    for i in range(1, n):
        for j in range(i):
            if arr[i] > arr[j]:
                dp[i] = max(dp[i], dp[j] + 1)

    # max_length = max(dp)  # 直接从 dp 数组中找到最大值
    return dp  # 返回最长上升子序列的长度

# 示例数组
arr = [1, 8, 2, 3, 4, 5]
print(longest_increasing_subsequence(arr))