In [1]:
import numpy as np

In [14]:
a = np.arange(12).reshape(3,4)
print('a:',a)
b = np.ones((4,3))
print('b:',b)
print('c:',np.dot(a,b)) # 矩阵乘法（点乘）
a.dot(b) # a本身将发生改变
a

a: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c: [[ 6.  6.  6.]
 [22. 22. 22.]
 [38. 38. 38.]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])