In [1]:
import numpy as np

In [2]:
np.triu(np.ones((3,3)), k=0)

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [4]:
np.triu(np.ones((3,3)), k=1)

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.triu(arr,k=1)

# 上3角区域保持不变
# 其他地方变成0


array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [2]:
a = np.random.randint(0,10,(2,2))
b = np.random.randint(0,10,(2,2))
print('-'*6)
print(a)
print('-'*6)
print(b)

------
[[6 7]
 [0 9]]
------
[[5 5]
 [3 1]]


In [3]:
# 这个一般用在哪里呢？！！！
np.fmax(a,b)  # 从a，b的对应位置处找到最大的值

array([[6, 7],
       [3, 9]])

In [4]:
np.where(a>b,a,b) # 有条件又有对应条件的值，则返回对应条件的值

array([[6, 7],
       [3, 9]])

In [6]:
a=np.random.randn(2,2)
a

array([[ 1.47911334,  0.99931994],
       [-1.20981012,  0.02686326]])

In [8]:
a.min(1)

array([ 0.99931994, -1.20981012])

In [9]:
a = np.arange(9)
res = np.where(a>2) # # 当只有条件时，返回索引
res

(array([3, 4, 5, 6, 7, 8], dtype=int64),)

In [10]:
res[0]

array([3, 4, 5, 6, 7, 8], dtype=int64)

In [5]:
h_array = np.zeros(100, dtype=np.int32)
np.where(h_array==0)[0] # 当只有条件时，返回索引

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int64)

In [7]:
a = np.arange(9)
np.where(a>2,'yes','no')

array(['no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'],
      dtype='<U3')

In [9]:
a = np.arange(9)
np.where(a>2,'yes','no')

array(['no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'],
      dtype='<U3')

In [11]:
# 主动使用广播机制
a = np.array([1,2,3])
b = np.broadcast_to(a,(3,3))
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [4]:
print(np.max([1,2]))
print(max([1,2]))

2
2


In [1]:
import numpy as np

In [3]:
a = np.array([123, 2, 255, 289])
a

array([123,   2, 255, 289])

In [7]:
np.where(a>255, 255, a)

array([123,   2, 255, 255])

In [5]:
np.uint8(a)

array([123,   2, 255,  33], dtype=uint8)

In [2]:
[1,2,3,4,5,5,5].index(5)

4

In [3]:
[1,2,3,4,5,5,5].index(1)

0