In [1]:
import numpy as np

In [2]:
shape=(3,4)
a = np.empty(shape, dtype=object)
print(a)

[[None None None None]
 [None None None None]
 [None None None None]]


In [10]:
shape=(4,4)
a = np.full(shape, None, dtype=object)
print(a)

[[None None None None]
 [None None None None]
 [None None None None]
 [None None None None]]


In [12]:
[np.full((2, 51),None, dtype=object)  for _ in range(2)   ] 

[array([[None, None, None, None, None, None, None, None, None, None, None,
         None, None, None, None, None, None, None, None, None, None, None,
         None, None, None, None, None, None, None, None, None, None, None,
         None, None, None, None, None, None, None, None, None, None, None,
         None, None, None, None, None, None, None],
        [None, None, None, None, None, None, None, None, None, None, None,
         None, None, None, None, None, None, None, None, None, None, None,
         None, None, None, None, None, None, None, None, None, None, None,
         None, None, None, None, None, None, None, None, None, None, None,
         None, None, None, None, None, None, None]], dtype=object),
 array([[None, None, None, None, None, None, None, None, None, None, None,
         None, None, None, None, None, None, None, None, None, None, None,
         None, None, None, None, None, None, None, None, None, None, None,
         None, None, None, None, None, None, None, None

In [11]:
a.dtype

dtype('O')

In [21]:
a = np.random.permutation(12)
print(f'len(a)={len(a)},a:{a}, ---- {sorted(a)}')

len(a)=12,a:[ 8  9  5  2  4  0  3 10  1 11  7  6], ---- [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [25]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [26]:
arr = np.array([[0],[1]])
arr

array([[0],
       [1]])

In [32]:
for i in range(10):
    a = np.random.permutation(2)
    a
    print('='*8)
    print(arr[a])

[[0]
 [1]]
[[1]
 [0]]
[[0]
 [1]]
[[1]
 [0]]
[[0]
 [1]]
[[0]
 [1]]
[[0]
 [1]]
[[1]
 [0]]
[[1]
 [0]]
[[1]
 [0]]


In [36]:
left_img = [ np.ones((3,5,5)), np.ones((3,5,5))*2 ]
right_img = [ np.ones((3,5,5))*3, np.ones((3,5,5))*4 ]

a = np.array([left_img, right_img])
print(a.shape)

(2, 2, 3, 5, 5)


In [37]:
a

array([[[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]],

         [[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]]]],



       [[[[3., 3., 3.,

In [24]:
for i in range(10):
    print(np.random.permutation(2))

[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[0 1]
[1 0]
[0 1]
[0 1]
[1 0]


In [3]:
arr = np.array([[2,4],[3,6]])
arr

array([[2, 4],
       [3, 6]])

In [6]:
np.arange(start=1,stop=10,step=3) # 不包括stop本身
# help(np.arange) # 查看 np,arange()的具体用法

array([1, 4, 7])

<span style='color:red;'>1. 生成确定数值的数组</span>

In [19]:

np.linspace(start=1, stop=100, num=12) # 等差数列
a = np.zeros([12,4]) # 生成全 0 数组
np.zeros_like(a) # 生成 形状和a一样且元素全是0的数组
np.ones(10, dtype=np.int) # 同理 
# 生成单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<span style='color:red;'>2.生成随机数组</span>

In [25]:
# 0-1均匀分布
print('-='*5, '0-1均匀分布' ,'-='*5)
print('随机生成1个数：',np.random.rand())
print('随机生成3个数：',np.random.rand(3))
print('随机生成3*2个数：',np.random.rand(3,2))
# 0-1正态分布
print('-='*5, '0-1正态分布' ,'-='*5)
print('随机生成1个数：',np.random.randn())
print('随机生成3个数：',np.random.randn(3))
print('随机生成3*2个数：',np.random.randn(3,2))
# 指定范围的整数
print('-='*5, '随机生成指定范围的整数' ,'-='*5)
print('随机生成10个指定范围的整数',np.random.randint(low=0,high=10,size=10))
print('随机生成2*3个指定范围的整数',np.random.randint(low=0,high=10,size=(2,3)))

-=-=-=-=-= 0-1均匀分布 -=-=-=-=-=
随机生成1个数： 0.658846172805777
随机生成3个数： [0.16592613 0.09971218 0.51588762]
随机生成3*2个数： [[0.7632574  0.58615211]
 [0.40876537 0.5377827 ]
 [0.08978321 0.87654259]]
-=-=-=-=-= 0-1正态分布 -=-=-=-=-=
随机生成1个数： -0.7170711620212428
随机生成3个数： [ 0.21494653  0.94465756 -0.10719543]
随机生成3*2个数： [[-0.38991583  2.15424031]
 [-1.01695593  0.08787924]
 [-0.13687071 -1.2760126 ]]
-=-=-=-=-= 随机生成指定范围的整数 -=-=-=-=-=
随机生成10个指定范围的整数 [0 1 1 7 2 8 8 0 0 9]
随机生成2*3个指定范围的整数 [[7 7 8]
 [2 8 4]]


In [30]:
a = np.arange(10)
print('a:',a)
np.random.shuffle(a) # 注意： 可见打乱的是原数组
print('shuffle_a:',a)

a: [0 1 2 3 4 5 6 7 8 9]
shuffle_a: [7 0 6 8 9 3 2 5 1 4]


In [35]:
arr = np.arange(16).reshape(4,4)
print('arr:  ', arr)
print('arr.T:', arr.T)
print('arr.T:', arr.transpose(1,0))
print('arr.T:', arr.transpose())

arr:   [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
arr.T: [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
arr.T: [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
arr.T: [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


<span style='color:red;'> 3.数组的合并</span>

In [42]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[11,22,33,44],[55,66,77,88]])
print('concat-axis=0',np.concatenate([arr1,arr2], axis=0))
print('concat-axis=1',np.concatenate([arr1,arr2], axis=1))

concat-axis=0 [[ 1  2  3  4]
 [ 5  6  7  8]
 [11 22 33 44]
 [55 66 77 88]]
concat-axis=1 [[ 1  2  3  4 11 22 33 44]
 [ 5  6  7  8 55 66 77 88]]


In [6]:
a = np.array([1,2,3])
np.diag(a) # 当是一维数组时， 结果形成以一维数组为对角线元素的矩阵

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [11]:
a = np.arange(1,10).reshape(3,3)
print(a)
b = np.diag(a) # 当是二维数组时，结果输出对角线上的元素
b

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 5, 9])