In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
print(np.sum(a))
print('axis=0',np.sum(a,axis=0))
print('axis=1',np.sum(a,axis=1))

66
axis=0 [12 15 18 21]
axis=1 [ 6 22 38]


In [8]:
np.mean(a)
np.mean(a, axis=0)
np.mean(a, axis=1)

array([1.5, 5.5, 9.5])

In [10]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
np.max(a)
np.max(a,axis=0)
np.max(a,axis=1)

array([ 3,  7, 11])

In [25]:
import numpy as np  
  
x = np.array([1, 1, 2, 1, 2, 100]) # 统计range(0-max(x))从中各个元素出现的次数 
print(np.bincount(x))  # 输出：[0出现次数=0,1出现次数=3,2出现次数=3]  
print(np.argmax(np.bincount(x)))

[0 3 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
1


In [26]:
import numpy as np
labels, counts = np.unique(x, return_counts=True)  # 分类计数
print(labels) # [1 2 3]
print(counts) # [3 2 1]
print(labels[np.argmax(counts)])

[  1   2 100]
[3 2 1]
1


In [27]:
np.bincount([1,3,4])

array([0, 1, 0, 1, 1], dtype=int64)