In [1]:
import numpy as np

<span style='color:red'>1.轴排序</span>

In [2]:
a = np.random.randint(0,10,size=(3,4))
a

array([[3, 7, 4, 7],
       [6, 8, 3, 7],
       [4, 0, 6, 0]])

In [3]:
np.sort(a,axis=-1)

array([[3, 4, 7, 7],
       [3, 6, 7, 8],
       [0, 0, 4, 6]])

In [4]:
a

array([[3, 7, 4, 7],
       [6, 8, 3, 7],
       [4, 0, 6, 0]])

In [5]:
np.sort(a,axis=0)

array([[3, 0, 3, 0],
       [4, 7, 4, 7],
       [6, 8, 6, 7]])

<span style='color:red'>2.轴排序索引</span>

In [6]:
b = np.arange(12).reshape(3,4)
np.random.shuffle(b)
b

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [7]:
b

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [8]:
np.argsort(b,axis=-1)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [9]:
np.argsort(b,axis=0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]], dtype=int64)