In [2]:
import numpy as np

In [16]:
x = np.arange(4)
y = np.arange(4)
print('x:',x)
print('y:',y)
xx, yy = np.meshgrid(x,y)
print('xx:',xx)
print('yy:',yy)
xx_yy = np.concatenate([xx,yy],axis=-1)
print('xx_yy:',xx_yy)

x: [0 1 2 3]
y: [0 1 2 3]
xx: [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
yy: [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
xx_yy: [[0 1 2 3 0 0 0 0]
 [0 1 2 3 1 1 1 1]
 [0 1 2 3 2 2 2 2]
 [0 1 2 3 3 3 3 3]]


In [9]:
a = np.arange(1,17).reshape(4,4)
a        #上,下,左,右
np.pad(a,((1,2),(3,4)))

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  2,  3,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  5,  6,  7,  8,  0,  0,  0,  0],
       [ 0,  0,  0,  9, 10, 11, 12,  0,  0,  0,  0],
       [ 0,  0,  0, 13, 14, 15, 16,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [14]:
import numpy as np
# 方法一：从指定的列表中随机选择3个元素(又放回-里面可能有重复的)
sample = np.random.choice([1,2,3,4,5],size=3)
print(sample)
# 方式二：从0~9内选择5个不重复的元素
sample=np.random.choice(10,size=5,replace=False)
print(sample)
# 方式三：每个元素选择都指定对应的概率
sample=np.random.choice(3,size=2,p=[0.2,0.5,0.3],replace=False)
print(sample)

[5 5 3]
[6 4 8 9 2]
[1 0]


In [16]:
eye_data = np.eye(5)
eye_data

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
eye_data[[1,2,3]]

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [21]:
a_l = []
a_l.append([[1,2,3],[2,3,4]])
a_l

[[[1, 2, 3], [2, 3, 4]]]