In [1]:
import numpy as np

In [4]:
poly = np.array([
    [2,1],
    [4,1],
    [3,2],
    [1,2]
])
poly

array([[2, 1],
       [4, 1],
       [3, 2],
       [1, 2]])

In [12]:
poly[:,0], poly[:,1].max()

(array([2, 4, 3, 1]), 2)

In [2]:
np.__version__

'1.19.0'

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = np.ones((3,3))
a > 2
# a.dtype

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [16]:
# 找到所有的奇数
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [17]:
# 将数组中所有的奇数替换成 -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(arr%2==0,arr,-1)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [32]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 将数组中所有的奇数替换成 -1, 且不改变原数组
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [25]:
a = np.array([1,2,3])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.unique(a[a==b])

array([2, 4])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])


In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
cond1 = [ i if x == y else 100 for i, (x, y) in enumerate(zip(a,b))  # 列表推导式中，判断条件if .. else ..完备时， 放在 for 之前 
print(cond1)
cond2 = [ i for i, (x, y) in enumerate(zip(a,b)) if x == y  ]    # 列表推导式中，判断条件仅有if 时， 放在 if 之后
print(cond2)

[100, 1, 100, 3, 100, 5, 100, 7, 100, 100]
[1, 3, 5, 7]


In [55]:
arr = np.arange(9).reshape(3,3)
print('raw:',arr)
# arr[:,0], arr[:,1] = arr[:,1], arr[:,0]
tmp = arr[:,0].copy()
arr[:,0] = arr[:,1]
arr[:,1] = tmp


print('='*6)
print('arr:',arr)


raw: [[0 1 2]
 [3 4 5]
 [6 7 8]]
arr: [[1 0 2]
 [4 3 5]
 [7 6 8]]


In [60]:
arr = np.arange(9).reshape(3,3)
print(arr)
print('-'*6)
arr[:,::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [63]:
# 创建 形状为 5 * 3，大小为 [5,10]的数组 
np.random.rand(5,3) * 5 + 5

array([[5.41922904, 6.78493771, 6.51074105],
       [5.98577008, 7.1417595 , 9.55027314],
       [8.42200694, 8.10505327, 6.31057257],
       [7.06657717, 7.66968328, 6.14525752],
       [7.59834486, 5.90795723, 9.08731942]])

In [65]:
rand_arr = np.random.random((5,3))
rand_arr.round(3)

array([[0.138, 0.276, 0.8  ],
       [0.828, 0.373, 0.331],
       [0.491, 0.403, 0.135],
       [0.966, 0.56 , 0.467],
       [0.766, 0.029, 0.572]])

In [67]:
# 归一化
arr = np.array([10, 20, 30, 40, 50])
min_val, max_val = np.min(arr), np.max(arr)
print(min_val, max_val)
(arr - min_val)/(max_val-min_val)




10 50


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [70]:
arr = np.array([10, 20, 30, 40, 50])
arr/arr.sum()


array([0.06666667, 0.13333333, 0.2       , 0.26666667, 0.33333333])

In [72]:
def softmax(a):
    return np.exp(a)/np.exp(a).sum()
softmax(arr)

array([4.24816138e-18, 9.35719813e-14, 2.06106005e-09, 4.53978686e-05,
       9.99954600e-01])

In [73]:
def softmax(A):
    exp_A = np.exp(A)
    return exp_A / np.sum(exp_A)
softmax(arr)

array([4.24816138e-18, 9.35719813e-14, 2.06106005e-09, 4.53978686e-05,
       9.99954600e-01])

In [81]:
z = np.ones((10,10))
print('%.3f'%(z.size * z.itemsize))

800.000


In [82]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [86]:
z = np.arange(9).reshape(3,3)
print('z:',z)
for index, val in enumerate(z):
    print(index, val)

z: [[0 1 2]
 [3 4 5]
 [6 7 8]]
0 [0 1 2]
1 [3 4 5]
2 [6 7 8]
