In [1]:
import torch
import torch.nn as nn

f:\my_softers\project_IDE\Anconda\envs\jp_layout_pytorch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [83]:
num_layer=1
bidirectional_flag=False
rnn = nn.LSTM(input_size=10, 
              hidden_size=20, 
              num_layers=num_layer,
              bidirectional=bidirectional_flag,# 是否使用双向RNN，默认False
              batch_first=False # 是否让batch_size位于数据格式的前面，默认False
              )
input = torch.randn(5, #  序列长度
                    3, # batch_size
                    10) # 输入维度
h0 = torch.randn(num_layer*2 if bidirectional_flag else num_layer, 3, 20)
c0 = torch.randn(num_layer*2 if bidirectional_flag else num_layer, 3, 20)
output, (hn, cn) = rnn(input, (h0, c0))
print(output.shape) # （序列长度，batch，隐层大小*2）# 双向*2 ==>torch.Size([5, 3, 20])
print(hn.shape) # 双向 ===》（层数*2，batch，隐层大小）       ==>torch.Size([1, 3, 20])
                # 单向 ===》 (层数，  batch，隐层大小）
print('='*6)
print((hn[-1]==cn[-1]).all()) # False
print((output[-1]==hn[0]).all() )# 可见nn.LSTM每一个时刻的输出=每一时刻的隐变量) True

torch.Size([5, 3, 20])
torch.Size([1, 3, 20])
tensor(False)
tensor(True)


In [82]:
print((hn[-1]==cn[-1]).all())
print((output[-1]==hn[0]).all() )# 可见nn.LSTM每一个时刻的输出=每一时刻的隐变量)
# print(torch.equal(output[-1],hn[-1]) )

tensor(False)
tensor(True)


In [85]:
num_layer=1
rnn = nn.RNN(input_size=10, 
              hidden_size=20, 
              num_layers=num_layer,
              bidirectional=False
              )
input = torch.randn(5, #  序列长度
                    3, # batch_size
                    10) # 输入维度
h0 = torch.randn(num_layer, 3, 20)
output, hn = rnn(input, h0)
print(output.shape) # # （序列长度，batch，隐层大小*2）# 双向*2
print(hn.shape) # 双向 ===》（层数*2，batch，隐层大小）
                # 单向 ===》 (层数，  batch，隐层大小）
print((output[-1]==hn[-1]).all() )# 可见nn.RNN每一个时刻的输出=每一时刻的隐变量)

torch.Size([5, 3, 20])
torch.Size([1, 3, 20])
tensor(True)


In [36]:
# print((hn[-1]==cn[-1]).all())


tensor(True)


In [42]:
# 下面的代码直接套用文心一言的代码
import torch  
import torch.nn as nn  
  
# 参数设置  
input_size = 10  # 输入特征维度  
hidden_size = 20  # 隐藏层特征维度  
batch_size = 1    # 批次大小  
seq_len = 5       # 序列长度  
  
# 创建 LSTM 模型  
lstm = nn.LSTM(input_size, hidden_size, batch_first=True)  
  
# 随机输入数据  
input_data = torch.randn(batch_size, seq_len, input_size)  
  
# 初始化隐藏状态和细胞状态  
h0 = torch.zeros(1, batch_size, hidden_size)  # 隐藏状态  
c0 = torch.zeros(1, batch_size, hidden_size)  # 细胞状态  
  
# 将输入数据和初始状态传递给 LSTM  
output, (hn, cn) = lstm(input_data, (h0, c0))  
  
# 提取最后一个时间步的输出、隐藏状态和细胞状态  
last_output = output[:, -1, :]  # 最后一个时间步的输出  
final_hidden_state = hn.squeeze(0)  # 最后一个时间步的隐藏状态，移除层数维度  
final_cell_state = cn.squeeze(0)  # 最后一个时间步的细胞状态，移除层数维度  
  
# 打印结果以观察它们之间的差异  
print("Last Output:")  
print(last_output)  
print("\nFinal Hidden State:")  
print(final_hidden_state)  
print("\nFinal Cell State:")  
print(final_cell_state)  
  
# 验证最后一个时间步的输出与隐藏状态或细胞状态是否相同（应该会失败）  
print(torch.equal(last_output, final_hidden_state))# , "Last output and final hidden state are not equal"  
assert torch.equal(last_output, final_hidden_state), "Last output and final hidden state are not equal" 
# assert torch.equal(last_output, final_cell_state), "Last output and final cell state are not equal"

Last Output:
tensor([[ 0.0615,  0.1368, -0.1042, -0.0560,  0.2412, -0.0601,  0.1842,  0.1493,
          0.0370, -0.1467, -0.2329, -0.0135, -0.1350, -0.1628,  0.0863,  0.1768,
         -0.1316,  0.1020, -0.1518,  0.1980]], grad_fn=<SliceBackward0>)

Final Hidden State:
tensor([[ 0.0615,  0.1368, -0.1042, -0.0560,  0.2412, -0.0601,  0.1842,  0.1493,
          0.0370, -0.1467, -0.2329, -0.0135, -0.1350, -0.1628,  0.0863,  0.1768,
         -0.1316,  0.1020, -0.1518,  0.1980]], grad_fn=<SqueezeBackward1>)

Final Cell State:
tensor([[ 0.1535,  0.2058, -0.2509, -0.1164,  0.3932, -0.1687,  0.4186,  0.2870,
          0.0661, -0.2875, -0.5762, -0.0266, -0.2721, -0.4014,  0.2269,  0.4625,
         -0.2600,  0.3018, -0.3393,  0.2768]], grad_fn=<SqueezeBackward1>)
True
